### ISSUE TITLE
<<TOP URGENT>> Stocks are not showing

### ISSUE THREAD

**Issue by sabinsp09** [azharakbar/lafi-sa.issues#10]
**Describe the bug**
Stocks are not showing even after successful Stock Upload.
**To Reproduce**
1. Upload Stock List under any branch head
2. Stills Stocks Shows "Out of Stock"

**Comment by sabinsp09** [comment]
[Test .xlsx](https://github.com/azharakbar/lafi-sa.issues/files/4303004/Test.xlsx)
 For your reference

**Comment by sabinsp09** [comment]
To Reproduce
Steps to reproduce the behavior:

1- Sign in with "sabins@lafi-sa.com" (Stock Upload option for Sahari Branch)
2-GO to  Dashboard> Inventory > Upload Stock
3 Upload the given file for test purpose
4- message displayes with No Errors found.
5- Check the Stock Status.
6- Still it says " Out of Stock"
[Test .xlsx](https://github.com/azharakbar/lafi-sa.issues/files/4303005/Test.xlsx)

**Comment by azharakbar** [comment]
@sabinsp09 
Is this reproducible in newTest ?
Pls check and confirm

**Always mention this information in any issue raised by any staff**

**Comment by sabinsp09** [comment]
Is this reproducible in newTest ?
Yes. It is reproducible in new test. tested in the New test and same issue araising.

This issue noticed from yesterday as most of the stocks displays out of stock. I tried myself to update and same error of " out of stock" occurred.

**Comment by azharakbar** [comment]
I reset all stocks to zero
and checked the stock of CID-410CM by loigging in as sabins@lafi-sa.com

It was zero .. 

I uploaded the Test.xlsx given by you and checked, it was 30 beside Sahari Branch

Hence, i was not able to reproduce,

If there is some mistake in my steps pls inform @sabinsp09

**Comment by sabinsp09** [comment]
sabins@lafi-sa.com is mapped to sahari branch. If we try to upload the test file. the Stock should show 30 qty, but it says zero. But the stock upload is getting successful and no errors.

**Comment by sabinsp09** [comment]
Actually this is not any error of stock uploads. The stocks were there, and suddenly disappeared and now shows "Out of Stock" is the issue. Why this happened?

**Comment by azharakbar** [comment]
@sabinsp09 i have cleared stocks of all items in new_test, can u check by uploading the test sheet? And confirm whats the result

**Comment by sabinsp09** [comment]
Still the same. After Stock updation, it shows "Out of Stock "

**Comment by azharakbar** [comment]
@sabinsp09 
You uploaded the test.xl which was sent to me right ?

**Comment by sabinsp09** [comment]
Yes dear. Just test with that one item.

**Comment by azharakbar** [comment]
@sabinsp09 
![image](https://user-images.githubusercontent.com/10185101/76164926-bf334700-6178-11ea-83fa-bbfeabd97473.png)

It seems correct

**Comment by sabinsp09** [comment]
Let me check in newtest

**Comment by sabinsp09** [comment]
Oof. Now i understood the issue. Its while searching and checking the stock status.
![image](https://user-images.githubusercontent.com/61094152/76165024-a1f47d80-6164-11ea-972d-b6a38d4ad746.png)

**Comment by azharakbar** [comment]
@sabinsp09 
Tell me the reproducing steps

**Comment by sabinsp09** [comment]
1-Sign in with sabins@lafi-sa.com
2- Search for the item *CID-410CM*
3- Stock shows Out of Stock"

**Comment by azharakbar** [comment]
all others are correct ?

**Comment by sabinsp09** [comment]
Yes. Stock are correct except while searching. I checked in the Original Data base also. its the same issue. The stock uploaded in the Morning are showing correctly. But not through **Search Option**.

**Comment by azharakbar** [comment]
is the issue same in mainLine and newTest @sabinsp09  ?
Pls confirm in both places ..

**Comment by sabinsp09** [comment]
Yes. Confirm.

**Comment by azharakbar** [comment]
**RCA**
Usage of undefined variable in ``getItemStock`` model function
This got into mainLine code because of an unmerged performace change for SpecialOffers optimization

**Solution**
Updated the variable name to correct ones and updated the code change in required branch `[specialOfferFix]`

**Comment by azharakbar** [comment]
@sabinsp09 Fix is done, pls check and confirm

**Comment by sabinsp09** [comment]
Checked and Working Fine right now.
