### ISSUE TITLE
Given Serials are not displayed  properly

### ISSUE THREAD

**Issue by sabinsp09** [azharakbar/lafi-sa.issues#14]
**Given Serials are not showing as given**
Once the Serial Numbers of Product are given before dispatching the materials, It is not showing as given in the **View Serial of a Product** Page

**To Reproduce**
1. Go to Order No: 50523
2. Click on "View Serial Numbers of Product"

**Expected behavior**
The allocated serial of a Product is displayed in another item. Also sometimes the "%" like characters are not displaying. (serial numbers always will not be just numeric. sometime it comes with extra characters also)

**Screenshots**
![image](https://user-images.githubusercontent.com/61094152/83618158-b8a74680-a592-11ea-8825-e05ee7338d44.png)

**Additional context**
The original Serial that has to be displayed is given as .txt in the attachment and also pasted below for your reference
**KX-TES824SU**
%9KCCN027858
%9LACN028053

**KX-TS880B**
%7BATA263353
%8EATA282614

**KX-TE82494**
%9ECKJ157726
%9ECKJ157725

**KX-T7705**
%9LAKH611552
%9LAKH611553
%9LAKH611554
[Original Serials.txt](https://github.com/azharakbar/lafi-sa.issues/files/4722168/Original.Serials.txt)

**Comment by azharakbar** [comment]
@sabinsp09
Good explanation of bug.. Keep it up.. Will fix soon

**Comment by azharakbar** [comment]
@sabinsp09 The fix is merged to testing website. pls check and confirm the fix
Pls apply valid labels if fixed or not fixed
