### ISSUE TITLE
VAT Rate is going to increase from 5% to 15% from July 1st onwards

### ISSUE THREAD

**Issue by sabinsp09** [azharakbar/lafi-sa.issues#16]
**Change of VAT rate to 15% instead of 5% implementations has to be made in our Quote & Invoices**
As per GAZT new announcement, From First July 2020 onwards the VAT Rate has to be set 15% in all our Quotes and Invoices which is prepared through our website. 

GAZT VAT related new article for your reference: https://gazt.gov.sa/en/HelpCenter/guidelines/Documents/Transitional%20Provisions%20Guidelines%20of%20VAT%20Rate%20Increase%20to%2015.pdf

**Comment by azharakbar** [comment]
**RCA**
The VAT percentage shown on `myCart` page was fixed to 5%, even though the calculation was based on the values fed from adminSide

The issue was with the view side only

**Comment by azharakbar** [comment]
@sabinsp09 
Pls check that the issue is fixed
If fixed, pls apply the label solution-verified, else apply solution-incorrect
