### ISSUE TITLE
Disable VAT Rate Change option to saleman

### ISSUE THREAD

**Issue by sabinsp09** [azharakbar/lafi-sa.issues#18]
**Describe the bug**
In the current scenario, while preparing quotations, we can change the VAT rate percentage to any number. there is an Up and Down arrow is displayed which make this option possible. As the Govt rate is fixed(15%). So that option should be disabled otherwise it may lead to change the VAT rate by billers while preparing Quote by accident. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Put any items to "Make a Quote"
2. Click on "List of Quote"
3. Scroll down to 'VAT'
4. See the issue

**Expected behavior**
The option to change VAT rate should be disabled.

**Screenshots**
![error 10-08](https://user-images.githubusercontent.com/61094152/89808627-1b90fd00-db43-11ea-95c9-9c3e5aa11a6f.jpg)

**Comment by azharakbar** [comment]
@sabinsp09 Pls confirm the change

**Comment by sabinsp09** [comment]
Still we are getting this option to change the VAT Rate. Could you please check ?
![image](https://user-images.githubusercontent.com/61094152/90045243-6b083200-dcd7-11ea-9c78-0b45f4aa12ff.png)

**Comment by azharakbar** [comment]
@sabinsp09 
Where are you checking?
Pls check in the testing website ... 
After the solution verified there, then only will be seen in the main website .. 

Pls check in the test website

**Comment by sabinsp09** [comment]
Sorry my bad. let me check in testing site

**Comment by sabinsp09** [comment]
Dear, thank you for disabling VAT rate. But please note that it testing site, the percentage is 5%. hope you will keep in mind that the current rate is 15% while you compile with the original.
![image](https://user-images.githubusercontent.com/61094152/90051009-ac9cdb00-dcdf-11ea-85f9-76c54a7a9f93.png)
