### ISSUE TITLE
Delivery Complete- OTP is not received to Recipient Mobile

### ISSUE THREAD

**Issue by sabinsp09** [azharakbar/lafi-sa.issues#19]
**Describe the bug**
As a part of Completing our received Order. the final option is to close the Order by sending an OTP of *Order Delivery Confirmation* message to the Customer. But currently, that OTP system is not working. Customers are complaining that they are not receiving any SMS from our side.

**To Reproduce**
1. Go to any ongoing Order which has completed all Levels except to close "ON THE WAY"
2. Click on 'DELIVERED'
3. Generate OTP
4. But, the concerned Recipient is not receiving the SMS

**Expected behavior**
The message has to be delivered to customer to close the Order.

**Comment by azharakbar** [comment]
**RCA**
The credentials of SMS Service Provider was incorrect
Other internal issues [Mentioned in PR]

**Comment by azharakbar** [comment]
@sabinsp09 Pls confirm the fix

**Comment by sabinsp09** [comment]
Working Fine. Now customers are receiving the OTP without delay.
