### ISSUE TITLE
Downloaded PDF Failed to Open error

### ISSUE THREAD

**Issue by sabinsp09** [azharakbar/lafi-sa.issues#2]
The bug is Downloaded PDF is getting failed to open. 
We have created a new Quote (Quote no: 10869 ) and after downloading the created quote, the pdf is failed to open. we are getting the error "Failed to load PDF document.".

Steps to reproduce:
1- Signed in Using mujeeb@lafi-sa.com
2- Created a Quote with random items. added a new item in the quote using "new item" (which is not in our database)
3-Given print option and downloaded the quote PDF.
4- After download, when we try to open. this error is coming
( **You can also try to download the current created Quote No: 10869 in the Quote Database and check the issue**)

This same behavior when try to add a new quote using the same items. (Quote 10867 is the previous quote with same error issue)

NB: the mentioned quote is created under mujeeb@lafi-sa.com user.
![error](https://user-images.githubusercontent.com/61094152/74594092-7be72c00-5043-11ea-9b15-0482934548e2.JPG)

**Comment by azharakbar** [comment]
@majeedpalakkal 
Pls verify this ticket and information is correct and reproducible in ``new_test`` or not

**Comment by azharakbar** [comment]
if verified, then add appropriate label as per the README

**Comment by azharakbar** [comment]
The issue was with the version ``6.2.3`` of ``tcpdf`` that was used in mainLine server
It is updated to the latest version ``6.3.2``
The issue seems to be solved

**Comment by sabinsp09** [comment]
@azharakbar You mean update the PDF software ?

**Comment by azharakbar** [comment]
Yes
Pls check and verify the issue is solved or not

**Comment by sabinsp09** [comment]
Ok. Let me check now.

**Comment by sabinsp09** [comment]
Currently working fine.♥

**Comment by azharakbar** [comment]
Ok, thank you
Issue will be closed now
