### ISSUE TITLE
Item file Export to excel failure

### ISSUE THREAD

**Issue by majeedpalakkal** [azharakbar/lafi-sa.issues#4]
**https://www.lafi-sa.com/new_test/manage**

Item file export to excel is is a failure
**To Reproduce**
1. Go to 'https://www.lafi-sa.com/new_test/manage'
2. Click on 'Items/Manage'
3. Select the Products/Category/Model, then Filter & Seach 
4. 5 Export to excel

**Expected behavior**
The excel file downloads, but when it try to open, it shows an error message in excel sheet

![image](https://user-images.githubusercontent.com/60974793/74601566-a3c0a900-50b0-11ea-8346-46db851f2791.png)

**Comment by azharakbar** [comment]
It was a bug in PHPExcel module which is a 3rd party code that we use to prepare excel sheets with PHP
This issue were reported earlier by other people also
https://myprestamodules.com/faqs/solutions-of-modules-errors/php-fatal-error-break-not-in-the-loop-or-switch-context.html

Illegal use ``break`` is removed from the vendor code

**Comment by majeedpalakkal** [comment]
Thanks, we can close this issue
