### ISSUE TITLE
Order placement doesn't save to database, but email generates

### ISSUE THREAD

**Issue by majeedpalakkal** [azharakbar/lafi-sa.issues#6]
**Order didn't show**
Mr. Sajeev reported me that his customer placed an order and he received the email message, but doesn't show in my order list.  The same issue was happened before and I had reported to you.  He says that order No. 50511 and 50512 was the recent order, but not there.  When I checked the order list in admin I found that the last serial number we received is 50506, that means 5 orders we missed which is a serious bug

**To Reproduce**
I don't have any idea how to reproduce the error.

**Expected behavior**
No idea why it's happening, but this issue is happening recently.

**Screenshots**

![image](https://user-images.githubusercontent.com/60974793/74720658-2bd8b700-5247-11ea-81d1-f02b7acb395d.png)

![image](https://user-images.githubusercontent.com/60974793/74720686-35621f00-5247-11ea-887e-3b884ed80d0f.png)

**Additional context**

**Comment by azharakbar** [comment]
@majeedpalakkal the issue is reproduced
Will fix soon

**Comment by azharakbar** [comment]
**Reproduction steps**
In the final step, continuously press GO BACK and PLACE ORDER button

**Comment by majeedpalakkal** [comment]
The customer tried to place an order and he got an error message which are pasted below.  But his second trial not made issue

![image](https://user-images.githubusercontent.com/60974793/74824541-5eeb7b00-5319-11ea-856c-fb8e7ca4ca6c.png)

**Comment by azharakbar** [comment]
It is due to the multiplication operation being carried on a ``string`` datatype value

Fix:
Typecast to ``float`` using ``floatval``
